config/routes.rb
Rails.application.routes.draw do
  
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  
  # Defines the root path route ("/")
  # root "articles#index"
  
  root "projects#index", as: :projects
  get "projects/:id", to: "projects#show", as: :project
  
  get "musings/index", to: "musings#index", as: :musings
  get "musings/:id", to: "musings#show", as: :musing
  
  get "about", to: "pages#about", as: :about
  get "download_resume", to: "pages#download_resume", as: :download_resume

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/content.rb
class Content < ApplicationRecord
  belongs_to :musing
end

app/models/musing.rb
class Musing < ApplicationRecord
  has_many :contents, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord
  has_many :slides, dependent: :destroy
end

app/models/slide.rb
class Slide < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/musings_controller.rb
class MusingsController < ApplicationController

  def index
    @musings = Musing.all
  end

  def show
    @musing = Musing.find(params[:id])
    @contents = Musing.find(params[:id]).contents
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def download_resume
    send_file "#{Rails.root}/app/assets/docs/kevinkim_cv.pdf", type: "application/pdf", x_sendfile: true
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  
  def index
    @projects = Project.all
  end

  def work
    @projects = Project.all
  end

  def show
    @project = Project.find(params[:id])
    @slides = Project.find(params[:id]).slides
  end

end

app/controllers/slides_controller.rb
class SlidesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/musings_helper.rb
module MusingsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/slides_helper.rb
module SlidesHelper
end

app/views/layouts/_footer.html.erb
<div class="footer">
  <div class="footer-container">

    <div class="footer-left">
      <div id="footer-header">Contact</div>
      <ul>
        <li>Kevin Kim</li>
        <li>hello@kevinrkim.com</li>
        <li><a href="https://www.linkedin.com/in/kevinrkim">LinkedIn</a></li>
      </ul>
    </div>

    <div class="footer-right">
      This website was developed from the ground up using Ruby on Rails. All original web design, code, and graphics were produced by me.
    </div>

  </div>
</div>

app/views/layouts/_navbar.html.erb
<% @project ? navbar_color = @project.banner_bg_color : navbar_color = "#FFFFFF" %>
<% @project ? navbar_text = @project.banner_text_color : navbar_text = "#333333" %>

<%# define link text styling %>
<style>
  .navbar-link-colored {
    color: <%= navbar_text %> !important;
  }
</style>

<ul class="navbar-container" style="background-color: <%= navbar_color %>;">
  <div class="navbar-links">
    <li class="navbar-link"><%= link_to "Work", projects_path(anchor: "work"), class:"navbar-link-text navbar-link-colored" %></li>
    <li class="navbar-link"><%= link_to "About", about_path, class:"navbar-link-text navbar-link-colored" %></li>
  </div>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Kevin Kim Portfolio</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="<%= controller_name %>-<%= action_name %>-view" >
    <%= render "layouts/navbar" %>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>

app/views/musings/index.html.erb
<div class="baseline-container">
  <h2>Musings</h2>
  <h4 id="musings-index-subtitle">A collection of my thoughts and opinions on product design, user experience, and corporate brand identity.</h4>

  <div class="index-grid-container">
  <% musings = [] %>
  <% @musings.each do |musing| %>
    <% musings << musing %>
  <% end %>
  <% musings_sorted = musings.sort_by{|m| m.created_at }.reverse %>
  <% musings_sorted.each do |musing| %>
    <div class="index-grid-item">
      <%= link_to musing_path(musing), class:"musings-link" do %>
        <%= image_tag "#{musing.image}", id:"musing-thumbnail" %>
        <div id="musing-title">
          <%= musing.title %>
        </div>
      <% end %>
      <div id="musing-date">
        <%= musing.created_at.strftime("%B %Y") %>
      </div>
    </div>
  <% end %>
  </div>
</div>

app/views/musings/show.html.erb
<div class="baseline-container">
  <h2 id="musing-show-title"><%= @musing.title %></h2>
  <h3 id="musing-show-date"><%= @musing.created_at.strftime("%B %Y") %></h3>

  <% contents = [] %>
  <% @contents.each do |content| %>
    <% contents << content %>
  <% end %>
  <% contents_sorted = contents.sort_by{|s| s.position} %>
  <% contents_sorted.each do |content| %>
    <% if content.image %>
      <div class="content-image">
        <%= image_tag content.image %>
        <div class="content-image-caption">
          <%= content.text_content %>
        </div>
      </div>
    <% else %>
      <p class="content-text">
        <%= content.text_content %>
      </p>
    <% end %>
  <% end %>

</div>

app/views/pages/about.html.erb
<div class="baseline-container">

  <h2>About Kevin Kim</h2>
  <div id="about-body">
    <p id="about-text">When I was six years old, I rode the Seoul subway for the first time. I remember staring at the map with fascination — the colorful subway paths drew me in, but it was the message behind those lines that kept me engaged. I learned where my grandmother’s stop was located on the purple line, and from that moment on, the city opened up to me like a book that was begging to be read.

  The map was a minimalist abstraction of the city in which the only written characters were the names of the stops and the map legend. Yet somehow, this colorful weave of lines against the plain white background spoke volumes to me. Every time we went somewhere by subway, I insisted on locating our destination on the map and guiding us there. The more transfers, the better; I was always eager to trace out our paths, identify our transfer points, and go from one color to the next.

  This is my earliest memory of appreciating good design. Even today, I have a particular fondness for subway maps and their ability to take the concrete chaos of a large city and create visual simplicity and order for the users. When I was six years old, I may not have understood the deliberate design techniques used to make the Seoul subway map so effective, but I did feel a great deal of satisfaction in making sense of the intricately placed lines and circles. In my professional life today, I constantly think about how a product, experience, or visualization can be crafted to bring that same sense of satisfaction and ease of use to the user.

  I was born and raised in Seattle but have called New York home since 2010. Having family in Korea and Italy, and also having traveled a lot during my work as a consultant, I have spent a lot of time on the go appreciating the differences in the way people live, think, and interact with their environments. I often find myself thinking about the way things are, observing little details in the way things are designed, with the aim of bringing joy to others through my own empathy and intellect.</p>
    <div id="about-photo-container">
      <%= image_tag "/assets/about/bio-photo.jpg", id:"about-photo" %>
      <%= link_to "Download CV", download_resume_path %>
    </div>
    
  </div>

  <div id="about-subway-map">
      <%= image_tag "/assets/about/map.png" %>
  </div>
  <div class="content-image">
    <div class="content-image-caption caption-frame">
      My journey (so far)
   </div>
  </div>

</div>

app/views/projects/index.html.erb
<div class="baseline-container" id="work-top">

  <h2>Hi! I'm Kevin.</h2>
  <h2 class="intro-text">
  Strategist<br>
  Full stack developer<br>
  Product person
  </h2>
  <p id="intro-paragraph">I spent the first chapter of my career as a management consultant working with clients across many industries — cable, media, retail to name a few. I built the foundation of my career on business strategy, but I’ve expanded my focus in recent years towards product and design. 

At a certain point in my career, I was becoming painfully aware of the limitations of a one-page resume. I spent years working with clients to transform complex information into visually engaging materials to facilitate the exchange of ideas. I thought to myself, surely, consultants can do the same with their resumes! This also happened to come at a time when I was learning how to become a full-stack software developer. This career portfolio ended up becoming a modest output of the skills I picked up along that journey. 

I created the graphics used in this portfolio as illustrative snapshots of the deliverables I produced for my clients. If you’d like to see a classic one-page resume, you can find that under the About section.

I hope this portfolio gives you a brief but insightful look into my career so far. If there’s something you’d like to know more about or if you’d just like to chat, please feel free to drop me a line!
  </p>
  <div id="firms-container">
    <div id="firms-image">
      <%= image_tag "/assets/work/firms.png" %>
    </div>
  </div>
  <div class="content-image">
    <div class="content-image-caption caption-frame">
      Firms I worked at over the years
   </div>
  </div>
  <div id="work-arrow-down" class="arrow-activate">
    <%= image_tag "/assets/work/arrow.png", class:"work-arrow" %>
  </div>
  <div id="work"></div>
  <div id="work-arrow-up">
    <%= image_tag "/assets/work/arrow.png", class:"work-arrow" %>
  </div>
  <h2>Work</h2>
  <h4 id="work-subtitle">Projects I've worked on throughout my career as a management consultant. This is not a fully comprehensive list, but a curated collection of my work that best represents my experience.</h4>
  <div class="index-grid-container">
    <% @projects.each do |project| %>
      <%= link_to project_path(project), class:"index-grid-item project-grid-item" do %>
        <%= image_tag "#{project.thumbnail}" %>
        <%= project.title %>
      <% end %>
    <% end %>
  </div>

</div>

app/views/projects/show.html.erb
<% banner_height = @project.banner_height %>
<% banner_bg_color = @project.banner_bg_color %>
<% banner_text = @project.banner_text_color %>
<% banner_subtext = @project.banner_subtext_color %>

<%# added the below line to make the iphone notch color blend in with background bg color %>
<meta name="theme-color" content="<%= banner_bg_color %>"/>

<div
  class="project-banner"
  style="background-color: <%= banner_bg_color %>;">


  <div class="project-show-container">
    <div class="project-header">
      <div class="project-header-left">
        <h2 class="project-title" style="color: <%= banner_text %>;"><%= @project.title %></h2>
        <h3 style="color: <%= banner_subtext %>;"><%= @project.client_name %></h3>
      </div>
      <div class="project-header-right">
        <h6 style="color: <%= banner_text %>;"><%= @project.blurb %></h6>
      </div>
    </div>
  </div>


  <% upper_padding = @project.banner_upper_padding %>
  <% lower_padding = @project.banner_lower_padding %>
  <div
    class="project-banner-image"
    style="
      padding-top: <%= upper_padding %>;
      padding-bottom: <%= lower_padding %>;
      height: <%= banner_height %>;"
  >
    <%= image_tag @project.banner %>
  </div>

</div>

<div class="page-background">
  <div class="project-show-container">

    <div class="project-details">
      <div class="project-details-left">
        <% if @project.start_year == @project.end_year %>
          <h3 class="project-years"><%= @project.start_year %></h3>
        <% else %>
          <h3 class="project-years"><%= "#{@project.start_year}" + "-" + "#{@project.end_year}" %></h3>
        <% end %>
        <h3 class="company-name"><%= @project.company %></h3>
      </div>
      <div class="project-details-right">
        <p><%= @project.description %></p>
      </div>
    </div>

    <div class="slide-grid-container">
      <% @slides.each do |slide| %>
        <div class="slide-grid-item">
          <div class="slide-grid-left">
            <%= image_tag slide.image %>
          </div>
          <div class="slide-grid-right">
            <h5 class="slide-title"><%= slide.title %></h5>
            <p><%= slide.description %></p>
          </div>
        </div>
      <% end %>

    </div>

  </div>
</div>  